// createJSON.js
// Author : Drumsticks1
// GitHub : https://github.com/Drumsticks1/TS3-LogDataViewer

"use strict";

const fs = require("fs"),
    Constants = require("./Constants.js"),
    globalVariables = require("./globalVariables.js"),
    miscFunctions = require("./miscFunctions.js"),
    outputHandler = require("./outputHandler.js");

var parsedLogs =  globalVariables.parsedLogs,
    ClientList = globalVariables.ClientList,
    ServerGroupList = globalVariables.ServerGroupList,
    BanList = globalVariables.BanList,
    KickList = globalVariables.KickList,
    ComplaintList = globalVariables.ComplaintList,
    UploadList = globalVariables.UploadList;

/**
 * Creates a json containing the data extracted from the logs.
 */
exports.createJSON = function() {
    outputHandler.output("Starting JSON creation...");

    miscFunctions.updateCurrentDate();
    var json = {
        "Attributes":{
            "Generated by": "TS3-LogDataViewer",
            "virtualServer": globalVariables.virtualServer,
            "creationTimestamp_LocalTime": miscFunctions.getCurrentLocaltime(),
            "creationTimestamp_UTC": miscFunctions.getCurrentUTC()
        },
        "parsedLogs":parsedLogs,
        "ClientList":ClientList,
        "ServerGroupList":ServerGroupList,
        "BanList":BanList,
        "KickList":KickList,
        "ComplaintList":ComplaintList,
        "UploadList":UploadList
    };

    try{
        fs.writeFileSync(Constants.outputJSON, JSON.stringify(json), 'utf8');
    }
    catch(error){
        outputHandler.output("An error occurred while creating the JSON:\n" + error.message);
        return 0;
    }

    outputHandler.output("JSON creation completed.");
};